### PR TITLE
Make it work in Debian (pkg-config)

### PR DESCRIPTION
**Pull request by UMLAUTaxl**
Debian (or any new distro) doesn't have  pkgconf but pkg-config

### CODE REVIEW

**Comment by BlueWinds** [comment]
I'd honestly sort of forgotten I had this fork, but I'm glad people are finding a use for it! Always happy to accept fixes.

**Comment by UMLAUTaxl** [comment]
Hmm, seems there is pkgconf for Debian. I still have the old pkg-config installed so it wouldn't work for me. My bad. Maybe roll back. Or create another branch?

**Comment by BlueWinds** [comment]
I went ahead and added support for both. Still works on my machine (with pkg-config), but should now work with pkgconf as well.

**Comment by UMLAUTaxl** [comment]
Cool. Thanks!

**Pull request merged**
